# Generated by Django 4.2 on 2024-01-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='dob',
        ),
        migrations.AddField(
            model_name='faculty',
            name='doj',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
