# Generated by Django 4.2 on 2024-01-02 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_faculty_dob_faculty_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='doj',
            field=models.DateField(default=datetime.date(2024, 1, 2), null=True),
        ),
    ]
